
site_name: Meine Dokumentation
theme:
  language: de
  name: material
  features:
    - navigation.sections
    - navigation.tabs

plugins:
  - search

extra:
  alternate:
    - name: English
      link: ../en/
      lang: en
    - name: Deutsch
      link: .
      lang: de
